# Generated by Django 3.2.5 on 2021-07-14 05:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('id', models.PositiveIntegerField(unique=True)),
                ('height', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('image', models.ImageField(max_length=255, upload_to='pokemon_images/', verbose_name='Изображение покемона')),
                ('base_happiness', models.PositiveIntegerField()),
                ('capture_rate', models.PositiveIntegerField()),
                ('has_gender_differences', models.BooleanField()),
                ('is_baby', models.BooleanField()),
                ('is_legendary', models.BooleanField()),
                ('is_mythical', models.BooleanField()),
                ('is_playing', models.BooleanField(default=False)),
                ('user', models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='пользователи')),
            ],
        ),
    ]
